[package]
name = "surreal-bug-check"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.19.0"
surrealdb = "1.4.2"
tokio = { version = "1.37.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
